FROM node:14.16.0-alpine as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# RUN npm i react-scripts@4.0.3 -g

COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build

RUN find . -path ./node_modules -type f

# Build prod image
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
