services:
  server:
    container_name: server-prod
    build:
      context: server
      # TODO: Create prod Dockerfile
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - server/.env
  client:
    container_name: client-prod
    build:
      context: client
      dockerfile: Dockerfile.prod
    ports:
      - 8081:80
